@host=http://localhost:5000/v1/

### Test
GET {{host}}/hello

### All users
GET {{host}}/users

### An user
GET {{host}}/users/1

### Add user
POST {{host}}/users/save
Content-Type: application/json

{
    "first_name": "John",
    "last_name": "Doe",
    "email": "john@test.com",
    "password": "123456",
    "avatar_id": 2
}

### Update user
POST {{host}}/users/save
Content-Type: application/json

{
    "id": 15,
    "first_name": "John",
    "last_name": "Doe",
    "email": "john@test.com",
    "password": "azerty",
    "avatar_id": 3
}

### Delete user
DELETE {{host}}/users/delete/15





### All messages
GET {{host}}/messages

### A message
GET {{host}}/messages/1

### Add message
POST {{host}}/messages/save
Content-Type: application/json

{
    "from": "Tim Cook",
    "email": "tim@apple.com",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi fringilla sollicitudin erat tincidunt pulvinar. Etiam lectus dolor, aliquet a sollicitudin sed, tempor in purus. Mauris ac nulla vel tellus sagittis vestibulum. Nam et magna ut elit lacinia laoreet ac in felis. Maecenas ac tellus neque. Proin sed urna nibh."
}

### Delete message
DELETE {{host}}/messages/delete/4






### All posts
GET {{host}}/posts

### A post
GET {{host}}/posts/1

### Add post
POST {{host}}/posts/save
Content-Type: application/json

{
    "title": "Potatoes in Texas",
    "subtitle": "Because nobody talk about it...",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi fringilla sollicitudin erat tincidunt pulvinar. Etiam lectus dolor, aliquet a sollicitudin sed, tempor in purus. Mauris ac nulla vel tellus sagittis vestibulum. Nam et magna ut elit lacinia laoreet ac in felis. Maecenas ac tellus neque. Proin sed urna nibh.",
    "user_id": 1,
    "image_id": 3
}

### Update post
POST {{host}}/posts/save
Content-Type: application/json

{
    "id": 6,
    "title": "Potatoes in Yukon",
    "subtitle": "Because nobody talk about it...",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi fringilla sollicitudin erat tincidunt pulvinar. Etiam lectus dolor, aliquet a sollicitudin sed, tempor in purus. Mauris ac nulla vel tellus sagittis vestibulum. Nam et magna ut elit lacinia laoreet ac in felis. Maecenas ac tellus neque. Proin sed urna nibh.",
    "user_id": 1,
    "image_id": 3
}

### Delete post
DELETE {{host}}/posts/delete/3





### All projects
GET {{host}}/projects

### A project
GET {{host}}/projects/1

### Add project
POST {{host}}/projects/save
Content-Type: application/json

{
    "title": "The New LinkedIn",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi fringilla sollicitudin erat tincidunt pulvinar. Etiam lectus dolor, aliquet a sollicitudin sed, tempor in purus. Mauris ac nulla vel tellus sagittis vestibulum. Nam et magna ut elit lacinia laoreet ac in felis. Maecenas ac tellus neque. Proin sed urna nibh.",
    "github_link": "test",
    "web_link": "test",
    "user_id": 1,
    "image_id": 2
}

### Update project
POST {{host}}/projects/save
Content-Type: application/json

{
    "id": 3,
    "title": "The New Twitter",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi fringilla sollicitudin erat tincidunt pulvinar. Etiam lectus dolor, aliquet a sollicitudin sed, tempor in purus. Mauris ac nulla vel tellus sagittis vestibulum. Nam et magna ut elit lacinia laoreet ac in felis. Maecenas ac tellus neque. Proin sed urna nibh.",
    "github_link": "test",
    "web_link": "toto",
    "user_id": 1,
    "image_id": 4
}

### Delete project
DELETE {{host}}/projects/delete/5






### All avatars
GET {{host}}/avatars

### A avatar
GET {{host}}/avatars/1

### Add avatar
POST {{host}}/avatars/save
Content-Type: application/json

{
    "name": "Test",
    "url": "http://trtsdfgsdgdf.fg/"
}

### Delete avatar
DELETE {{host}}/avatars/delete/5





### All images
GET {{host}}/images

### A image
GET {{host}}/images/1

### Add image
POST {{host}}/images/save
Content-Type: application/json

{
    "name": "Test",
    "url": "http://trtsdfgsdgdf.fg/"
}

### Delete image
DELETE {{host}}/images/delete/5






### All technos
GET {{host}}/technos

### A techno
GET {{host}}/technos/1

### Add techno
POST {{host}}/technos/save
Content-Type: application/json

{
    "name": "Test",
    "image": "http://trtsdfgsdgdf.fg/"
}

### Delete techno
DELETE {{host}}/technos/delete/5